name: Discord Alert

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Test webhook
        run: |
          echo "Enviando mensagem..."
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" \
          -H "Content-Type: application/json" \
          -d '{"content":"🚀 TESTE FINAL DISCORD"}' \
          "${{ secrets.DISCORD_WEBHOOK }}")

          echo "HTTP STATUS: $RESPONSE"
          echo "Resposta:"
          cat response.txt